drop TABLE rexdb_test_student;

$$

CREATE TABLE rexdb_test_student (
  STUDENT_ID NUMBER(11) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  SEX NUMBER(1) NOT NULL,
  BIRTHDAY DATE NOT NULL,
  BIRTH_TIME DATE NOT NULL,
  ENROLLMENT_TIME DATE NOT NULL,
  MAJOR NUMBER(6) NOT NULL,
  PHOTO BLOB,
  REMARK CLOB,
  READONLY NUMBER(1) NOT NULL,
  PRIMARY KEY (STUDENT_ID)
);

$$